function type(obj) {
  console.log(Object.prototype.toString.call(obj).match(/\[object\s|\]/g))
  return Object.prototype.toString.call(obj).replace(/\[object\s|\]/g, '')
}
console.log(type([]))
console.log(type(1))
console.log(type(undefined))
console.log(type(true))
console.log(type({}))
console.log(type('a'))
console.log(type(null))
console.log(`------------------------------------`)
console.log(typeof null)
console.log(typeof undefined)
console.log(typeof {})
console.log(typeof [])
console.log(typeof 1)
console.log(typeof '1')
console.log(typeof true)
